{"name": "test_contact_us_negative[--]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Tests.tests.TestAllPages object at 0x0000018866DDBF40>, Email = '', Contact_name = '', message = ''\n\n    @allure.description('Test contact us with different inputs ')\n    @allure.step\n    @allure.severity(allure.severity_level.CRITICAL)\n    @pytest.mark.parametrize(\"Email, Contact_name, message\",\n                             [\n                                 (\"\", \"one\", \"there is bug in contact page please fix it\"),\n                                 (\"123ab@gmail.com\", \"\", \"i cant find relevant message\"),\n                                 (\"ab123@gmail.com\", \"love\", \"\"),\n                                 (\"\", \"\", \"how can i take the path for assertion for invalid login?\"),\n                                 (\"abcd@gmail.com\", \"\", \"\"),\n                                 (\"\", \"onelove\", \"\"),\n                                 (\"\", \"\", \"\")])\n    def test_contact_us_negative(self, Email, Contact_name, message):\n        self.setup_demoblaze()\n        self.click(By.XPATH, self.CONTACT_US)\n        self.fields(By.ID, self.CONTACT_EMAIL, Email)\n        self.fields(By.ID, self.CONTACT_NAME, Contact_name)\n        self.fields(By.ID, self.MESSAGE, message)\n        self.click(By.XPATH, self.SEND_MESSAGE)\n>       self.alert_ok_button(\"Fill the blank \")\n\ntests.py:139: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Tests.tests.TestAllPages object at 0x0000018866DDBF40>, popup = 'Fill the blank ', time = 10\n\n    def alert_ok_button(self, popup, time: int = 10):\n        wait = WebDriverWait(self.driver, time)\n        wait.until(ec.alert_is_present())\n    \n        alert = self.driver.switch_to.alert\n>       assert popup in alert.text\nE       AssertionError\n\n..\\Base_Page\\base_pages.py:52: AssertionError"}, "description": "Test contact us with different inputs ", "steps": [{"name": "test_contact_us_negative", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\PycharmProjects\\pythonProject1\\FinalProject\\Tests\\tests.py\", line 139, in test_contact_us_negative\n    self.alert_ok_button(\"Fill the blank \")\n  File \"C:\\Users\\user\\PycharmProjects\\pythonProject1\\FinalProject\\Base_Page\\base_pages.py\", line 52, in alert_ok_button\n    assert popup in alert.text\n"}, "parameters": [{"name": "Email", "value": "''"}, {"name": "Contact_name", "value": "''"}, {"name": "message", "value": "''"}], "start": 1675539725741, "stop": 1675539727484}], "parameters": [{"name": "Email", "value": "''"}, {"name": "Contact_name", "value": "''"}, {"name": "message", "value": "''"}], "start": 1675539725740, "stop": 1675539727486, "uuid": "049c4030-100d-4650-96ed-f91ad8ef9ee8", "historyId": "c3ba72321191bf801a7d792f973ef181", "testCaseId": "06b713d1ff8c5633d53c69737b537625", "fullName": "tests.TestAllPages#test_contact_us_negative", "labels": [{"name": "severity", "value": "critical"}, {"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestAllPages"}, {"name": "host", "value": "gman-2121"}, {"name": "thread", "value": "31860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}